complete homework (23 October)
ZalyalovIldar/OperationQueueAndDispatchSwift pull request #1
Opened 2017-10-27 11:49 UTC by timbaev

2017-10-29 20:22 UTC, ZalyalovIldar requested changes
Нужно немного правок, а так не плохо!)

2017-10-29 20:22 UTC, ZalyalovIldar commented on VKProfile/Controllers/NoteViewController.swift
> +            if (insertResult) {
лучше назвать возвращаемое значение понятнее, раз у тебя там должен вернуться true, если все ок, то и назвать стоит isSaved - так будет понятнее что ты ожидаешь, а то кажется, что ожидается какой-то абстрактный "результат вставки"

2017-10-29 20:22 UTC, ZalyalovIldar commented on VKProfile/Controllers/NoteViewController.swift
> +                self.createNewsDelegate?.createNews(from: news)
это блок, а в блоке мы селфы делаем weak)

2017-10-29 20:22 UTC, ZalyalovIldar commented on VKProfile/Controllers/ViewController.swift
> +        NewsRepository.instance.syncSave(with: news3)
эхх был бы метод который сохранял массив, возможно было бы удобнее))  
Смотри сам конечно, тут просто пометка)

2017-10-29 20:22 UTC, ZalyalovIldar commented on VKProfile/Controllers/ViewController.swift
> +                self.tableView.reloadData()
в блоке не забывай делать self - weak self как мы делали)

2017-10-29 20:22 UTC, ZalyalovIldar commented on VKProfile/Repository/NewsRepository.swift
> +    private init() {}
это тут лишнее, думаю

2017-10-29 20:22 UTC, ZalyalovIldar commented on VKProfile/Repository/NewsRepository.swift
> +            self.currentID += 1
блок и strong self != гуд, делаем weak, если нужно через guard.

2017-10-29 20:22 UTC, ZalyalovIldar commented on VKProfile/Repository/NewsRepository.swift
> +        sortedNews.forEach { newsArray.append($0.value) }
зачем тут такие телодвижение с доп массивом?

2017-10-29 20:22 UTC, ZalyalovIldar commented on VKProfile/Repository/NewsRepository.swift
> +            completionBlock(newsResult)
блок и weak == good 
давай в остальных местах сам глянь по блокам)

2017-10-29 20:22 UTC, ZalyalovIldar commented on VKProfile/Controllers/ViewController.swift
> +            self.tableView.reloadData()
Достал синхронно, значит достал в главном сейчас, значит главный поток ждет пока у тебя завершится метод, и только потом приступит к обновлению таблицы. 
А отсюда 2 ошибочки: 
1) у тебя и так весь код выполняется в главном потоке, так что обновление таблицы не нужно помещать и форсить в главном, она и так будет в главном без DispatchQueue :) 
2) внутри блоков делаем self weak :)

2017-10-29 20:22 UTC, ZalyalovIldar commented on VKProfile/Controllers/DetailsNewsViewController.swift
> +        NewsRepository.instance.asyncSearch(id: newsID) { (resultNews) in
помимо темы с weak self в блоке, еще почему то этот поиск работает только со средней картинкой. Т.е. у тебя 3 картинки, если ткнуть на 1-ую сверху - то будет картинка/инфа 3-ей новости, если ткнуть на 3-ую будет картинка/инфа 1-ой новости, а вот с той что по середке все ок работает, глянь тоже)

2017-10-29 22:33 UTC, timbaev commented on VKProfile/Repository/NewsRepository.swift
> +        sortedNews.forEach { newsArray.append($0.value) }
Проблема в том, что новости хранятся в словаре (ID : Новость). А словарь по дефолту неупорядоченный. То есть, я буду получать массив новостей вразброс, поэтому и пришлось сначала упорядочить по ID-шникам, а дальше отправить. Но думаю, можно придумать и решение поэлегантнее.

2017-11-11 10:28 UTC, ZalyalovIldar approved these changes

2017-11-11 10:28 UTC, closed without merging