Homework added.
ZalyalovIldar/OperationQueueAndDispatchSwift pull request #4
Opened 2017-10-31 17:53 UTC by EliFBatyrova

Регистрации и авторизации пока нет

2017-11-01 20:14 UTC, EliFBatyrova commented
Добавила регистрацию и авторизацию

2017-11-11 11:18 UTC, ZalyalovIldar requested changes
Нормас, давай правочки :)

2017-11-11 11:18 UTC, ZalyalovIldar commented on VKapp/VK/View Cintrollers/ViewController.swift
> +        NewsManager.sharedInstance.syncSave(with: new4)
было бы удобно иметь сохранение массива думаю))

2017-11-11 11:18 UTC, ZalyalovIldar commented on VKapp/VK/View Cintrollers/ViewController.swift
> +        reloadNewsData()
релоадить нужно внутри блока, блок же у тебя асинхронный, так что ты должна быть уверена что блок завершил свою работу, а потом только ты обновляешь)

2017-11-11 11:18 UTC, ZalyalovIldar commented on VKapp/VK/View Cintrollers/ViewController.swift
> +            DispatchQueue.main.async {
внутри блока нужно делать ссылку [weak self], поправь по блокам где не сделала)

2017-11-11 11:18 UTC, ZalyalovIldar commented on VKapp/VK/Protocols/FormsValidationProtocol.swift
> +    func formsAreIncorrect() -> UIAlertController
твой метод звучит как поле модели, какое то булевое поле)) 
Назови чтобы было понятно типа "getErrorOkAlert" - если ты хотела просто возвращать алерт, у которого по сути текста никакого нет и только 1 кнопка "Ок", согласись так понятнее будет)
Назови протокол так, чтобы тоже понятно было что ты тут алерты возвращаешь))

2017-11-26 18:28 UTC, ZalyalovIldar approved these changes

2017-11-26 18:28 UTC, closed without merging